---
- name: Configure Nginx Docker Containers
  hosts: webcontainers
  gather_facts: false

  tasks:
    - name: Step 1 - Use raw to install Python inside the container
      raw: apt-get update && apt-get install -y python3

    - name: Step 2 - Now we can use standard Ansible modules!
      copy:
        dest: /usr/share/nginx/html/index.html
        content: |
          <html>
            <body style="background-color: lightblue;">
              <h1>Success! Ansible installed Python and created this page.</h1>
            </body>
          </html>
